### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by webignition** [webignition/basil-worker-handler#60]
- [x] webignition/basil-worker-persistence-bundle#28
- [x] webignition/basil-worker-state-bundle#24
- [x] webignition/string-prefix-remover#5
- [x] webignition/symfony-messenger-json-message-serializer-bundle#13
- [x] webignition/http-history-container#81
- [x] webignition/symfony-test-service-injector-trait#7
